// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'a_test.dart' as a_test;
import 'nested/b_test.dart' as nested_b_test;

void main() {
  a_test.main();
  nested_b_test.main();
}
